### ISSUE TITLE
Understanding your code and comparing with mine

### ISSUE THREAD

**Issue by SpaceApe1** [cevor/udacity_predictive_analytics#1]
Hi Cevor,

my name ist Kai. I am from Germany and also attempt the Udacity DataTrack (Predictive Analytics for Business Nanodegree Program) this year.
I am 34 years old and have never programmed any larger python scripts before starting this course.
In the project 6 I struggled with all the stuff around and my result differed a lot from my colleges that send me their Alterxy result for comprising. So I searched reference codes and found yours.

I just want to say thank you very much for sharing this code.
It helps me a lot, because your code already made me refactor a large part of the whole project. 
I think I might be able to finish the course with an accurat result too. Thanks to your help ;)

Best regards
Kai

**Comment by cevor** [comment]
Thank you for your email.

I real never thought my repo could be any help.

Please let connect after you graduate.

**Comment by SpaceApe1** [comment]
Dear Kavumo,

I also would like to stay in contact with you.
You can also write me at ***@***.***

Have you programmed some python before?

Kind regards
Kai



Am Fr., 15. Okt. 2021 um 14:39 Uhr schrieb Kavumo Mfinanga <
***@***.***>:

> Thank you for your email.
>
> I real never thought my repo could be any help.
>
> Please let connect after you graduate.
>

**Comment by cevor** [comment]
Noted.

use below contact:
email: info[dot]cevor[@]gmail[dot]com
twitter: @cevor87
